pull_request_rules:
  - name: Assign yourself
    conditions:
      - -merged
      - -closed
      - base=main
    actions:
      assign:
        add_users:
          - "{{author}}"
          
  - name: Automatic merge on approval
    conditions:
      - -closed
      - -merged
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - base=main
    actions:
      merge:
        method: merge

  - name: Add conflict label
    conditions: 
      - -closed
      - -merged
      - conflict
    actions:
      comment:
        message: "@{{author}} Conflict 해결이 필요합니다!😥"
      label:
        add:
          - conflict

  - name: Remove conflict label
    conditions:
      - -closed
      - -merged
      - -conflict
    actions:
      label:
        remove:
          - conflict
