pull_request_rules:
  - name: Assign yourself and request reviews automatically
    conditions:
      - base=main
    actions:
      assign:
        add_users:
          - "{{author}}"
      request_reviews:
        users:
          - CoodingPenguin
          - changwoomon
          - bsm8734
          - opijae
          - osmosm7
          - peacecheejecake
          - dkswndms4782

  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=3"
      - "#changes-requested-reviews-by=0"
      - base=main
    actions:
      merge:
        method: merge
