name: Auto Update This Week Reviewer List

on:
  schedule:
    # 매주 일요일 새벽 0시
    - cron: 0 0 * * SUN
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.1.3
        with:
            python-version: '3.x'
            architecture: 'x64'
      
      - name: Current directory
        run: pwd
      
      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install requests
        
      - name: Update Reviewer List 
        run: |
          python .scripts/change_reviewer.py

      - name: Git Commit
        run: |
          git config --local user.email "coodingpenguin@gmail.com"
          git config --local user.name "CoodingPenguin"
          git add .
          git commit -m "Update this week reviewer list"
      
      - name: Git Push
        uses: ad-m/github-push-action@master
        with:
           branch: 'main'
