name: Auto Set Reviewers

on:
  pull_request:
    types: ['opened']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.1.3
        with:
            python-version: '3.x'
            architecture: 'x64'
      
      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install requests
        
      - name: Set Reviewers
        env:
          ACCESS_TOKEN: ${{secrets.access_token}}
          PR_ID: ${{github.event.pull_request.number}}
        run: |
          python .scripts/set_reviewer.py --token "$ACCESS_TOKEN" --id "$PR_ID"
